<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>DriveReadIndicator</RootNamespace>
    <AssemblyName>DriveReadIndicator</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsFormsWithCustomSubMain</MyType>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <OptionCompare>Binary</OptionCompare>
    <Nullable>disable</Nullable>
    <StartupObject>DriveReadIndicator.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Drawing" />
    <Import Include="System.Linq" />
    <Import Include="System.Windows.Forms" />
    <Import Include="Microsoft.VisualBasic" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainForm.Designer.vb">
      <DependentUpon>MainForm.vb</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
